name: PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pr-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo Hello from **forked** repo for PR
